/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekranlar;

import javax.swing.JOptionPane;

/**
 *
 * @author Şeyma
 */
public class CalismaOdaEkrani extends javax.swing.JFrame {

    /**
     * Creates new form CalismaOdaEkrani
     */
    public CalismaOdaEkrani() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        oda1HerkesPlatin = new javax.swing.JCheckBox();
        oda4HerkesPlatin = new javax.swing.JCheckBox();
        oda2HerkesPlatin = new javax.swing.JCheckBox();
        oda3HerkesPlatin = new javax.swing.JCheckBox();
        oda1ÜcretArea = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        oda2ÜcretArea = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        oda3ÜcretArea = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        oda4ÜcretArea = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        oda1Btn = new javax.swing.JButton();
        oda2Btn = new javax.swing.JButton();
        oda3Btn = new javax.swing.JButton();
        oda4Btn = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("ODA 1");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KAPASİTE:");

        jTextField1.setEditable(false);
        jTextField1.setText("3");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("FİYATLAR SAATLİKTİR.\n\n\n\nNORMAL ÜYELER:15 TL\n\n\nPLATİN ÜYELER:9 TL");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("ODA 2");

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KAPASİTE:");

        jTextField2.setEditable(false);
        jTextField2.setText("5");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(10);
        jTextArea2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("FİYATLAR SAATLİKTİR.\n\n\n\nNORMAL ÜYELER:25 TL\n\n\nPLATİN ÜYELER:15 TL");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("ODA 3");

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KAPASİTE:");

        jTextField3.setEditable(false);
        jTextField3.setText("2");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(10);
        jTextArea3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("FİYATLAR SAATLİKTİR.\n\n\n\nNORMAL ÜYELER:10 TL\n\n\nPLATİN ÜYELER:6 TL");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("ODA 4");

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("KAPASİTE:");

        jTextField4.setEditable(false);
        jTextField4.setText("7");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(10);
        jTextArea4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("FİYATLAR SAATLİKTİR.\n\n\n\nNORMAL ÜYELER:35 TL\n\n\nPLATİN ÜYELER:21 TL");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        oda1HerkesPlatin.setText("HERKES PLATİN");

        oda4HerkesPlatin.setText("HERKES PLATİN");

        oda2HerkesPlatin.setText("HERKES PLATİN");

        oda3HerkesPlatin.setText("HERKES PLATİN");

        oda1ÜcretArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda1ÜcretAreaActionPerformed(evt);
            }
        });

        jLabel17.setText("ÜCRET: ");

        jLabel18.setText("ÜCRET: ");

        jLabel19.setText("ÜCRET: ");

        jLabel20.setText("ÜCRET: ");

        oda1Btn.setText("Ücret Al");
        oda1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda1BtnActionPerformed(evt);
            }
        });

        oda2Btn.setText("Ücret Al");
        oda2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda2BtnActionPerformed(evt);
            }
        });

        oda3Btn.setText("Ücret Al");
        oda3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda3BtnActionPerformed(evt);
            }
        });

        oda4Btn.setText("Ücret Al");
        oda4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda4BtnActionPerformed(evt);
            }
        });

        geriBtn.setText("GERİ");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oda1Btn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oda1ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(oda1HerkesPlatin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(oda2HerkesPlatin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(oda2Btn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oda2ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oda3HerkesPlatin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oda3ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oda3Btn)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oda4HerkesPlatin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oda4ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(oda4Btn))
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(geriBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oda4HerkesPlatin)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oda4ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(oda4Btn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oda3HerkesPlatin)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oda3ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(oda3Btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oda1HerkesPlatin)
                            .addComponent(oda2HerkesPlatin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oda1ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(oda2ÜcretArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oda2Btn)
                            .addComponent(oda1Btn))))
                .addGap(20, 20, 20)
                .addComponent(geriBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void oda1ÜcretAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda1ÜcretAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oda1ÜcretAreaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed
        MenuEkrani menuEkrani = new MenuEkrani();
        this.setVisible(false);
        menuEkrani.setVisible(true);

    }//GEN-LAST:event_geriBtnActionPerformed

    private void oda1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda1BtnActionPerformed
        if (!oda1ÜcretArea.getText().isEmpty()) {
            if (oda1HerkesPlatin.isSelected()) {
                //Herkesin platin olduğud durum
                final int ücret = 9;

                double ödenenPara = Integer.parseInt(oda1ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }

            } else {
                //Herkesin normal üye olduğu durum..
                final int ücret = 15;

                double ödenenPara = Integer.parseInt(oda1ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ücreti Giriniz..", "İşlem Başarısız", JOptionPane.PLAIN_MESSAGE);

        }


    }//GEN-LAST:event_oda1BtnActionPerformed

    private void oda2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda2BtnActionPerformed
        if (!oda2ÜcretArea.getText().isEmpty()) {
            if (oda2HerkesPlatin.isSelected()) {
                //Herkesin platin olduğud durum
                final int ücret = 15;

                double ödenenPara = Integer.parseInt(oda2ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }

            } else {
                //Herkesin normal üye olduğu durum..
                final int ücret = 25;

                double ödenenPara = Integer.parseInt(oda2ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ücreti Giriniz..", "İşlem Başarısız", JOptionPane.PLAIN_MESSAGE);

        }

    }//GEN-LAST:event_oda2BtnActionPerformed

    private void oda3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda3BtnActionPerformed
       if (!oda3ÜcretArea.getText().isEmpty()) {
            if (oda3HerkesPlatin.isSelected()) {
                //Herkesin platin olduğud durum
                final int ücret = 6;

                double ödenenPara = Integer.parseInt(oda3ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }

            } else {
                //Herkesin normal üye olduğu durum..
                final int ücret = 10;

                double ödenenPara = Integer.parseInt(oda3ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ücreti Giriniz..", "İşlem Başarısız", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_oda3BtnActionPerformed

    private void oda4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda4BtnActionPerformed
        if (!oda4ÜcretArea.getText().isEmpty()) {
            if (oda4HerkesPlatin.isSelected()) {
                //Herkesin platin olduğud durum
                final int ücret = 21;

                double ödenenPara = Integer.parseInt(oda4ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }

            } else {
                //Herkesin normal üye olduğu durum..
                final int ücret = 35;

                double ödenenPara = Integer.parseInt(oda4ÜcretArea.getText());

                if (ödenenPara < ücret) {

                    JOptionPane.showMessageDialog(this, "Yetersiz Para..", "Tekrar Deneyin", JOptionPane.PLAIN_MESSAGE);

                } else {
                    double paraUstu = ödenenPara - ücret;
                    JOptionPane.showMessageDialog(this, paraUstu + "TL Para üstü miktarı", "Para Üstü", JOptionPane.PLAIN_MESSAGE);

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ücreti Giriniz..", "İşlem Başarısız", JOptionPane.PLAIN_MESSAGE);

        }
    }//GEN-LAST:event_oda4BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalismaOdaEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalismaOdaEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalismaOdaEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalismaOdaEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalismaOdaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geriBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton oda1Btn;
    private javax.swing.JCheckBox oda1HerkesPlatin;
    private javax.swing.JTextField oda1ÜcretArea;
    private javax.swing.JButton oda2Btn;
    private javax.swing.JCheckBox oda2HerkesPlatin;
    private javax.swing.JTextField oda2ÜcretArea;
    private javax.swing.JButton oda3Btn;
    private javax.swing.JCheckBox oda3HerkesPlatin;
    private javax.swing.JTextField oda3ÜcretArea;
    private javax.swing.JButton oda4Btn;
    private javax.swing.JCheckBox oda4HerkesPlatin;
    private javax.swing.JTextField oda4ÜcretArea;
    // End of variables declaration//GEN-END:variables
}
